version: 0.0
os: linux
files:
  - source: /
    destination: /root
hooks:
  ApplicationStop:
    - location: deploy/scripts/applicationStop.sh
      timeout: 300
      runas: root
  BeforeInstall:
    - location: deploy/scripts/beforeInstall.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: deploy/scripts/afterInstall.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: deploy/scripts/applicationStart.sh
      timeout: 300
      runas: root
  ValidateService:
    - location: deploy/scripts/validateService.sh
      timeout: 300
      runas: root
